Dev next (#8)
* getting started

* limit ci

* readme image link to bindplane site

* tune

* fix promql http check

* unify images

* finish getting started

* new defaults and sizing guidelines

* move migrate deployment to k8s job

* fix e2e

* expose version option

* set grace period correctly

* keep migrate container around for 24 hours

* do not generate

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -2,7 +2,13 @@ name: CI
 
 on:
   push:
+    branches:
+      - main
+      - dev
   pull_request:
+    branches:
+      - main
+      - dev
 
 jobs:
   lint:
@@ -97,6 +103,30 @@ jobs:
         uses: goreleaser/goreleaser-action@v6
         with:
           args: build --snapshot --clean
+
+  generated:
+    name: Generated files up to date
+    runs-on: ubuntu-latest
+    steps:
+      - name: Clone the code
+        uses: actions/checkout@v4
+
+      - name: Setup Go
+        uses: actions/setup-go@v5
+        with:
+          go-version-file: go.mod
+
+      - name: Run manifests and generate
+        run: |
+          make manifests
+          make generate
+
+      - name: Check generated files are up to date
+        run: |
+          git diff --exit-code || (
+            echo "::error::Repository has uncommitted changes after 'make manifests generate'. Run 'make manifests generate' and commit the changes."
+            exit 1
+          )
 
   api-docs:
     name: API docs up to date
